USE GADB;
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;

BEGIN TRANSACTION
    UPDATE manager_table
    SET nameOfManager = 'Ionita'
    WHERE  anuallyIncome = 2378;
    WAITFOR DELAY '00:00:05'
COMMIT TRANSACTION