USE practical_ex_seminar;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ ;/*READ COMMITTED ;*/

BEGIN TRANSACTION
    SELECT * FROM categories WHERE name = 'n1';

    WAITFOR DELAY '00:00:05';

    SELECT * FROM categories WHERE name = 'n1';
COMMIT TRANSACTION