USE GADB;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION
    SELECT *
    FROM manager_table;
    WAITFOR DELAY '00:00:10'
    SELECT *
    FROM manager_table;
COMMIT TRANSACTION